# BEGIN rafex thinkpad touchpad natural scrolling
Section "InputClass"
    Identifier "Rafex ThinkPad touchpad natural scrolling"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "NaturalScrolling" "true"
    Option "ScrollMethod" "twofinger"
EndSection
# END rafex thinkpad touchpad natural scrolling
