[colors.primary]
background = "#2d353b"
foreground = "#d3c6aa"

[colors.cursor]
cursor = "#a7c080"
text = "#2d353b"

[colors.selection]
background = "#4f5b51"
text = "#d3c6aa"

[colors.normal]
black = "#3c4841"
red = "#f85552"
green = "#8da101"
yellow = "#dfa000"
blue = "#3a94c5"
magenta = "#df69ba"
cyan = "#35a77c"
white = "#9da9a0"

[colors.bright]
black = "#708089"
red = "#f57d7a"
green = "#a6b83a"
yellow = "#e7b83d"
blue = "#5daed5"
magenta = "#e28dcc"
cyan = "#5bbf98"
white = "#d3c6aa"
