# Rafex Everforest: claro suave verdoso.
set $theme_bar_bg #f3f1dc
set $theme_bar_fg #3c4841
set $theme_separator #9da9a0
set $theme_active_bg #8da101
set $theme_active_fg #f3f1dc
set $theme_inactive_bg #e7e4c9
set $theme_inactive_fg #708089
set $theme_urgent_bg #f85552
set $theme_urgent_fg #f3f1dc
