# Rafex Everforest para Polybar.
# BEGIN rafex polybar theme
[colors]
background = #f3f1dc
foreground = #3c4841
separator = #9da9a0
active = #8da101
active-foreground = #f3f1dc
inactive = #e7e4c9
inactive-foreground = #708089
urgent = #f85552
urgent-foreground = #f3f1dc
# END rafex polybar theme
