# Rafex Everforest: claro suave verdoso.
set -g pane-border-style "fg=#9da9a0"
set -g pane-active-border-style "fg=#8da101"
set -g message-style "fg=#3c4841,bg=#e7e4c9,bold"
set -g message-command-style "fg=#3c4841,bg=#dfe2bd"
set -g mode-style "fg=#3c4841,bg=#dfe2bd"
set -g status-style "bg=#f3f1dc,fg=#3c4841"
set -g status-left-length 80
set -g status-right-length 160
set -g status-left "#[fg=#f3f1dc,bg=#8da101,bold] #S #[fg=#8da101,bg=#f3f1dc]#{?window_zoomed_flag,#[fg=#3c4841,bg=#e7e4c9] zoom ,}"
set -g status-right "#[fg=#708089] #{b:pane_current_path} #[fg=#8da101] %H:%M #[fg=#708089] %d/%m"
setw -g window-status-format "#[fg=#708089,bg=#f3f1dc] #I:#W#{?window_flags,#{window_flags},} "
setw -g window-status-current-format "#[fg=#f3f1dc,bg=#8da101,bold] #I:#W#{?window_flags,#{window_flags},} "
setw -g window-status-separator ""
setw -g window-status-activity-style "fg=#a96b2c,bg=#f3f1dc"
