# Rafex Everforest: terminal oscuro suave verdoso.
set -g pane-border-style "fg=#9da9a0"
set -g pane-active-border-style "fg=#8da101"
set -g message-style "fg=#2d353b,bg=#a7c080,bold"
set -g message-command-style "fg=#d3c6aa,bg=#4f5b51"
set -g mode-style "fg=#d3c6aa,bg=#4f5b51"
set -g status-style "bg=#2d353b,fg=#d3c6aa"
set -g status-left-length 80
set -g status-right-length 160
set -g status-left "#[fg=#2d353b,bg=#a7c080,bold] #S #[fg=#a7c080,bg=#2d353b]#{?window_zoomed_flag,#[fg=#2d353b,bg=#dbbc7f] zoom ,}"
set -g status-right "#[fg=#708089] #{b:pane_current_path} #[fg=#8da101] %H:%M #[fg=#708089] %d/%m"
setw -g window-status-format "#[fg=#859289,bg=#2d353b] #I:#W#{?window_flags,#{window_flags},} "
setw -g window-status-current-format "#[fg=#f3f1dc,bg=#8da101,bold] #I:#W#{?window_flags,#{window_flags},} "
setw -g window-status-separator ""
setw -g window-status-activity-style "fg=#dbbc7f,bg=#2d353b"
