# Magic Mouse — MacBook Pro Late 2012 (Bluetooth)
# Natural scrolling activado (comportamiento macOS)
Section "InputClass"
    Identifier "Magic Mouse"
    MatchProduct "Magic Mouse"
    Driver "libinput"
    Option "NaturalScrolling" "true"
EndSection
