# Rafex Paper para Polybar.
# BEGIN rafex polybar theme
[colors]
background = #f7f1e8
foreground = #2d2a26
separator = #a69b8f
active = #b45f06
active-foreground = #fffaf2
inactive = #e8ddd0
inactive-foreground = #665e56
urgent = #b3261e
urgent-foreground = #fffaf2
# END rafex polybar theme
