# Rafex Paper para tint2.
# BEGIN rafex theme
panel_background_id = 1
taskbar_background_id = 1
taskbar_active_background_id = 2
taskbar_urgent_background_id = 3
taskbar_name_font_color = #2d2a26 100
taskbar_name_active_font_color = #fffaf2 100
taskbar_name_urgent_font_color = #fffaf2 100
systray_background_id = 1
clock_font_color = #2d2a26 100
execp_font_color = #2d2a26 100
background_color1 = #f7f1e8 100
background_color2 = #b45f06 100
background_color3 = #b3261e 100
# END rafex theme
