#!/usr/bin/env bash
# shellcheck shell=bash
# thinkpad_i3_fragments_linux.sh v1.0.0
# Publicación por fragmentos para el i3 administrado de Rafex.
# Se debe sourcear después de thinkpad_config_guard_linux.sh.

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  printf '%s\n' 'Este archivo es una biblioteca; úsalo mediante source desde un script Rafex.' >&2
  exit 2
fi

RAFEX_I3_FRAGMENT_ROOT="${RAFEX_I3_FRAGMENT_ROOT:-${XDG_STATE_HOME:-$HOME/.local/state}/rafex/config-generated/thinkpad/i3}"
RAFEX_I3_FRAGMENT_DIR="$RAFEX_I3_FRAGMENT_ROOT/fragments"
RAFEX_I3_FRAGMENT_BASE="$RAFEX_I3_FRAGMENT_ROOT/base.conf"
RAFEX_I3_FRAGMENT_COMPOSED_MARKER='# Generated by rafex i3 fragment composer'

rafex_i3_fragment_name() {
  case "$1" in
    '# BEGIN rafex theme') printf 'theme' ;;
    '# BEGIN rafex i3-gaps') printf 'gaps' ;;
    '# BEGIN rafex ulauncher default') printf 'launcher' ;;
    '# BEGIN rafex conky') printf 'conky' ;;
    '# BEGIN rafex eww') printf 'eww' ;;
    '# BEGIN rafex feh wallpaper') printf 'wallpaper' ;;
    '# BEGIN rafex i3lock-color') printf 'lock' ;;
    '# BEGIN rafex clipboard') printf 'clipboard' ;;
    '# BEGIN rafex screenshots') printf 'screenshots' ;;
    '# BEGIN rafex ratmenu') printf 'ratmenu' ;;
    '# BEGIN rafex control-panel') printf 'control-panel' ;;
    '# BEGIN rafex control panel') printf 'control-panel' ;;
    '# >>> i3-laptop-controls managed >>>') printf 'controls' ;;
    '# BEGIN tablet-autorotation') printf 'autorotate' ;;
    '# BEGIN rafex xrandr-brightness') printf 'xrandr-brightness' ;;
    '# BEGIN rafex udiskie') printf 'udiskie' ;;
    '# BEGIN rafex controls') printf 'controls' ;;
    '# >>> rafex-picom-service managed >>>') printf 'picom' ;;
    *) return 1 ;;
  esac
}

rafex_i3_fragment_is_active() {
  local target="$1" resolved
  [[ -f "$target" || -L "$target" ]] || return 1
  resolved="$(readlink -f -- "$target" 2>/dev/null || printf '%s' "$target")"
  grep -Fqx "$RAFEX_I3_FRAGMENT_COMPOSED_MARKER" "$resolved" 2>/dev/null
}

rafex_i3_fragment_target() {
  local target="$1"
  readlink -f -- "$target" 2>/dev/null || printf '%s\n' "$target"
}

rafex_i3_fragment_strip_blocks() {
  local source="$1"
  awk '
    $0 == "# Generated by rafex i3 fragment composer" { next }
    function managed_begin(line) {
      return line ~ /^# BEGIN rafex (theme|i3-gaps|ulauncher default|conky|eww|feh wallpaper|i3lock-color|clipboard|screenshots|ratmenu|control-panel|control panel|controls)$/ || line == "# BEGIN tablet-autorotation" || line == "# BEGIN rafex xrandr-brightness" || line == "# BEGIN rafex udiskie" || line == "# >>> i3-laptop-controls managed >>>" || line == "# >>> rafex-picom-service managed >>>"
    }
    function managed_end(line) {
      return line ~ /^# END rafex (theme|i3-gaps|ulauncher default|conky|eww|feh wallpaper|i3lock-color|clipboard|screenshots|ratmenu|control-panel|control panel|controls)$/ || line == "# END tablet-autorotation" || line == "# END rafex xrandr-brightness" || line == "# END rafex udiskie" || line == "# <<< i3-laptop-controls managed <<<" || line == "# <<< rafex-picom-service managed <<<"
    }
    !inside && managed_begin($0) { inside=1; next }
    inside && managed_end($0) { inside=0; next }
    inside { next }
    /^[[:space:]]*include[[:space:]]+~\/.config\/i3\/rafex-bar-active\.conf[[:space:]]*$/ { next }
    { print }
  ' "$source"
}

rafex_i3_fragment_extract() {
  local source="$1" begin="$2" end="$3"
  awk -v begin="$begin" -v end="$end" '
    $0 == begin { inside=1; print; next }
    inside { print }
    inside && $0 == end { exit }
  ' "$source"
}

rafex_i3_fragment_extract_first() {
  local source="$1" begin end content
  shift
  for begin in "$@"; do
    case "$begin" in
      *'control panel') end='# END rafex control panel' ;;
      *'control-panel') end='# END rafex control-panel' ;;
      *'>>> i3-laptop-controls managed >>>') end='# <<< i3-laptop-controls managed <<<' ;;
      *'>>> rafex-picom-service managed >>>') end='# <<< rafex-picom-service managed <<<' ;;
      *) end="${begin/\# BEGIN/\# END}" ;;
    esac
    content="$(rafex_i3_fragment_extract "$source" "$begin" "$end")"
    if [[ -n "$content" ]]; then
      printf '%s\n' "$content"
      return 0
    fi
  done
  return 0
}

rafex_i3_fragment_seed() {
  local target="$1" resolved name begin end fragment base_tmp
  mkdir -p -- "$RAFEX_I3_FRAGMENT_DIR"
  chmod 700 -- "$RAFEX_I3_FRAGMENT_ROOT" "$RAFEX_I3_FRAGMENT_DIR"
  resolved="$(rafex_i3_fragment_target "$target")"
  [[ -f "$RAFEX_I3_FRAGMENT_BASE" ]] || {
    [[ -f "$resolved" ]] || return 0
    base_tmp="$(mktemp "$RAFEX_I3_FRAGMENT_ROOT/.base.XXXXXX")"
    rafex_i3_fragment_strip_blocks "$resolved" > "$base_tmp"
    mv -f -- "$base_tmp" "$RAFEX_I3_FRAGMENT_BASE"
    chmod 600 -- "$RAFEX_I3_FRAGMENT_BASE"
  }
  for name in theme gaps launcher conky eww wallpaper lock clipboard screenshots ratmenu control-panel autorotate xrandr-brightness udiskie controls picom; do
    case "$name" in
      theme) begin='# BEGIN rafex theme'; end='# END rafex theme' ;;
      gaps) begin='# BEGIN rafex i3-gaps'; end='# END rafex i3-gaps' ;;
      launcher) begin='# BEGIN rafex ulauncher default'; end='# END rafex ulauncher default' ;;
      conky) begin='# BEGIN rafex conky'; end='# END rafex conky' ;;
      eww) begin='# BEGIN rafex eww'; end='# END rafex eww' ;;
      wallpaper) begin='# BEGIN rafex feh wallpaper'; end='# END rafex feh wallpaper' ;;
      lock) begin='# BEGIN rafex i3lock-color'; end='# END rafex i3lock-color' ;;
      clipboard) begin='# BEGIN rafex clipboard'; end='# END rafex clipboard' ;;
      screenshots) begin='# BEGIN rafex screenshots'; end='# END rafex screenshots' ;;
      ratmenu) begin='# BEGIN rafex ratmenu'; end='# END rafex ratmenu' ;;
      control-panel) begin='# BEGIN rafex control panel'; end='# END rafex control panel' ;;
      autorotate) begin='# BEGIN tablet-autorotation'; end='# END tablet-autorotation' ;;
      xrandr-brightness) begin='# BEGIN rafex xrandr-brightness'; end='# END rafex xrandr-brightness' ;;
      udiskie) begin='# BEGIN rafex udiskie'; end='# END rafex udiskie' ;;
      controls) begin='# >>> i3-laptop-controls managed >>>'; end='# <<< i3-laptop-controls managed <<<' ;;
      picom) begin='# >>> rafex-picom-service managed >>>'; end='# <<< rafex-picom-service managed <<<' ;;
    esac
    fragment="$RAFEX_I3_FRAGMENT_DIR/$name.conf"
    [[ -e "$fragment" ]] || {
      case "$name" in
        controls)
          rafex_i3_fragment_extract_first "$resolved" \
            '# >>> i3-laptop-controls managed >>>' '# BEGIN rafex controls' > "$fragment" ;;
        control-panel)
          rafex_i3_fragment_extract_first "$resolved" \
            '# BEGIN rafex control panel' '# BEGIN rafex control-panel' > "$fragment" ;;
        *)
          rafex_i3_fragment_extract_first "$resolved" "$begin" > "$fragment" ;;
      esac
      [[ -s "$fragment" ]] || rm -f -- "$fragment"
      [[ ! -e "$fragment" ]] || chmod 600 -- "$fragment"
    }
  done
}

rafex_i3_fragment_compose() {
  local target="$1" resolved temporary name fragment
  resolved="$(rafex_i3_fragment_target "$target")"
  [[ -f "$RAFEX_I3_FRAGMENT_BASE" ]] || return 1
  temporary="$(mktemp "${resolved}.XXXXXX")"
  {
    printf '%s\n' "$RAFEX_I3_FRAGMENT_COMPOSED_MARKER"
    cat "$RAFEX_I3_FRAGMENT_BASE"
    for name in theme gaps launcher conky eww wallpaper lock clipboard screenshots ratmenu control-panel autorotate xrandr-brightness udiskie controls picom; do
      fragment="$RAFEX_I3_FRAGMENT_DIR/$name.conf"
      [[ -s "$fragment" ]] || continue
      printf '\n'
      cat "$fragment"
    done
    printf '\n%s\n' 'include ~/.config/i3/rafex-bar-active.conf'
  } > "$temporary"
  if [[ -f "$resolved" ]] && cmp -s "$temporary" "$resolved"; then
    rm -f -- "$temporary"
    return 0
  fi
  if [[ -f "$resolved" ]]; then
    chmod --reference="$resolved" "$temporary" 2>/dev/null || true
  else
    chmod 600 -- "$temporary"
  fi
  mv -f -- "$temporary" "$resolved"
}

rafex_i3_fragment_replace() {
  local target="$1" begin="$2" end="$3" block_file="$4" name fragment temporary
  rafex_i3_fragment_is_active "$target" || return 2
  name="$(rafex_i3_fragment_name "$begin")" || return 1
  rafex_i3_fragment_seed "$target"
  fragment="$RAFEX_I3_FRAGMENT_DIR/$name.conf"
  temporary="$(mktemp "${fragment}.XXXXXX")"
  cp -p -- "$block_file" "$temporary"
  chmod 600 -- "$temporary"
  if [[ -f "$fragment" ]] && cmp -s "$temporary" "$fragment"; then
    rm -f -- "$temporary"
  else
    mv -f -- "$temporary" "$fragment"
  fi
  rafex_i3_fragment_compose "$target"
}

rafex_i3_fragment_adopt() {
  local target="$1" resolved
  resolved="$(rafex_i3_fragment_target "$target")"
  [[ -f "$resolved" ]] || return 1
  rafex_i3_fragment_seed "$resolved"
  rafex_i3_fragment_compose "$resolved"
}
