# Rafex Dracula para Polybar.
# BEGIN rafex polybar theme
[colors]
background = #282a36
foreground = #f8f8f2
separator = #6272a4
active = #bd93f9
active-foreground = #282a36
inactive = #44475a
inactive-foreground = #d6d6d6
urgent = #ff5555
urgent-foreground = #282a36
# END rafex polybar theme
