# Rafex Dracula para tint2.
# BEGIN rafex theme
panel_background_id = 1
taskbar_background_id = 1
taskbar_active_background_id = 2
taskbar_urgent_background_id = 3
taskbar_name_font_color = #f8f8f2 100
taskbar_name_active_font_color = #282a36 100
taskbar_name_urgent_font_color = #282a36 100
systray_background_id = 1
clock_font_color = #f8f8f2 100
execp_font_color = #f8f8f2 100
background_color1 = #282a36 100
background_color2 = #bd93f9 100
background_color3 = #ff5555 100
# END rafex theme
