# Rafex Dracula: oscuro de alto contraste.
set -g pane-border-style "fg=#6272a4"
set -g pane-active-border-style "fg=#bd93f9"
set -g message-style "fg=#282a36,bg=#f1fa8c,bold"
set -g message-command-style "fg=#282a36,bg=#8be9fd"
set -g mode-style "fg=#282a36,bg=#8be9fd"
set -g status-style "bg=#282a36,fg=#f8f8f2"
set -g status-left-length 80
set -g status-right-length 160
set -g status-left "#[fg=#282a36,bg=#bd93f9,bold] #S #[fg=#bd93f9,bg=#282a36]#{?window_zoomed_flag,#[fg=#282a36,bg=#f1fa8c] zoom ,}"
set -g status-right "#[fg=#bdc3e6] #{b:pane_current_path} #[fg=#bd93f9] %H:%M #[fg=#bdc3e6] %d/%m"
setw -g window-status-format "#[fg=#bdc3e6,bg=#282a36] #I:#W#{?window_flags,#{window_flags},} "
setw -g window-status-current-format "#[fg=#282a36,bg=#bd93f9,bold] #I:#W#{?window_flags,#{window_flags},} "
setw -g window-status-separator ""
setw -g window-status-activity-style "fg=#f1fa8c,bg=#282a36"
