[colors.primary]
background = "#2e3440"
foreground = "#eceff4"

[colors.cursor]
cursor = "#88c0d0"
text = "#2e3440"

[colors.selection]
background = "#4c566a"
text = "#eceff4"

[colors.normal]
black = "#2e3440"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#5e81ac"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#d8dee9"

[colors.bright]
black = "#4c566a"
red = "#d57780"
green = "#b1cc9a"
yellow = "#f0d399"
blue = "#81a1c1"
magenta = "#c39dbd"
cyan = "#8fcbda"
white = "#eceff4"
