# Rafex Nord: claro azul grisáceo, tema inicial del perfil.
set $theme_bar_bg #e5e9f0
set $theme_bar_fg #2e3440
set $theme_separator #7b88a1
set $theme_active_bg #5e81ac
set $theme_active_fg #eceff4
set $theme_inactive_bg #d8dee9
set $theme_inactive_fg #4c566a
set $theme_urgent_bg #bf616a
set $theme_urgent_fg #eceff4
