# Rafex Nord para Polybar.
# BEGIN rafex polybar theme
[colors]
background = #e5e9f0
foreground = #2e3440
separator = #7b88a1
active = #5e81ac
active-foreground = #eceff4
inactive = #d8dee9
inactive-foreground = #4c566a
urgent = #bf616a
urgent-foreground = #eceff4
# END rafex polybar theme
