# Rafex Nord: claro azul grisáceo.
set -g pane-border-style "fg=#7b88a1"
set -g pane-active-border-style "fg=#5e81ac"
set -g message-style "fg=#2e3440,bg=#d8dee9,bold"
set -g message-command-style "fg=#2e3440,bg=#c7d0e0"
set -g mode-style "fg=#2e3440,bg=#c7d0e0"
set -g status-style "bg=#e5e9f0,fg=#2e3440"
set -g status-left-length 80
set -g status-right-length 160
set -g status-left "#[fg=#eceff4,bg=#5e81ac,bold] #S #[fg=#5e81ac,bg=#e5e9f0]#{?window_zoomed_flag,#[fg=#2e3440,bg=#d8dee9] zoom ,}"
set -g status-right "#[fg=#4c566a] #{b:pane_current_path} #[fg=#5e81ac] %H:%M #[fg=#4c566a] %d/%m"
setw -g window-status-format "#[fg=#4c566a,bg=#e5e9f0] #I:#W#{?window_flags,#{window_flags},} "
setw -g window-status-current-format "#[fg=#eceff4,bg=#5e81ac,bold] #I:#W#{?window_flags,#{window_flags},} "
setw -g window-status-separator ""
setw -g window-status-activity-style "fg=#8f6b26,bg=#e5e9f0"
